project_name: go-jenkins-editor

release:
  prerelease: auto

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
archives:
  - format: binary
checksum:
  disable: true
snapshot:
  name_template: "{{ .Tag }}-next"